// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: database-server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_database_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_database_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_database_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_database_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SavePatientInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PatientInfo   *PatientInfo           `protobuf:"bytes,2,opt,name=patient_info,json=patientInfo,proto3" json:"patient_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePatientInfoRequest) Reset() {
	*x = SavePatientInfoRequest{}
	mi := &file_database_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePatientInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePatientInfoRequest) ProtoMessage() {}

func (x *SavePatientInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePatientInfoRequest.ProtoReflect.Descriptor instead.
func (*SavePatientInfoRequest) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{4}
}

func (x *SavePatientInfoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SavePatientInfoRequest) GetPatientInfo() *PatientInfo {
	if x != nil {
		return x.PatientInfo
	}
	return nil
}

type SavePatientInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePatientInfoResponse) Reset() {
	*x = SavePatientInfoResponse{}
	mi := &file_database_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePatientInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePatientInfoResponse) ProtoMessage() {}

func (x *SavePatientInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePatientInfoResponse.ProtoReflect.Descriptor instead.
func (*SavePatientInfoResponse) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{5}
}

func (x *SavePatientInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_database_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{6}
}

func (x *GetPatientRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientInfo   *PatientInfo           `protobuf:"bytes,1,opt,name=patient_info,json=patientInfo,proto3" json:"patient_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_database_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetPatientResponse) GetPatientInfo() *PatientInfo {
	if x != nil {
		return x.PatientInfo
	}
	return nil
}

type PatientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Height        float32                `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientInfo) Reset() {
	*x = PatientInfo{}
	mi := &file_database_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientInfo) ProtoMessage() {}

func (x *PatientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_database_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientInfo.ProtoReflect.Descriptor instead.
func (*PatientInfo) Descriptor() ([]byte, []int) {
	return file_database_server_proto_rawDescGZIP(), []int{8}
}

func (x *PatientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatientInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PatientInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PatientInfo) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PatientInfo) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_database_server_proto protoreflect.FileDescriptor

const file_database_server_proto_rawDesc = "" +
	"\n" +
	"\x15database-server.proto\x12\bdatabase\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"h\n" +
	"\x16SavePatientInfoRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x128\n" +
	"\fpatient_info\x18\x02 \x01(\v2\x15.database.PatientInfoR\vpatientInfo\"3\n" +
	"\x17SavePatientInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x11GetPatientRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"N\n" +
	"\x12GetPatientResponse\x128\n" +
	"\fpatient_info\x18\x01 \x01(\v2\x15.database.PatientInfoR\vpatientInfo\"{\n" +
	"\vPatientInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x02R\x06height2\xb7\x02\n" +
	"\x0fDatabaseService\x12:\n" +
	"\x05Login\x12\x16.database.LoginRequest\x1a\x17.database.LoginResponse\"\x00\x12C\n" +
	"\bRegister\x12\x19.database.RegisterRequest\x1a\x1a.database.RegisterResponse\"\x00\x12X\n" +
	"\x0fSavePatientInfo\x12 .database.SavePatientInfoRequest\x1a!.database.SavePatientInfoResponse\"\x00\x12I\n" +
	"\n" +
	"GetPatient\x12\x1b.database.GetPatientRequest\x1a\x1c.database.GetPatientResponse\"\x00B\x1dZ\x1bunb.br/web-server/src/protob\x06proto3"

var (
	file_database_server_proto_rawDescOnce sync.Once
	file_database_server_proto_rawDescData []byte
)

func file_database_server_proto_rawDescGZIP() []byte {
	file_database_server_proto_rawDescOnce.Do(func() {
		file_database_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_server_proto_rawDesc), len(file_database_server_proto_rawDesc)))
	})
	return file_database_server_proto_rawDescData
}

var file_database_server_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_database_server_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: database.LoginRequest
	(*LoginResponse)(nil),           // 1: database.LoginResponse
	(*RegisterRequest)(nil),         // 2: database.RegisterRequest
	(*RegisterResponse)(nil),        // 3: database.RegisterResponse
	(*SavePatientInfoRequest)(nil),  // 4: database.SavePatientInfoRequest
	(*SavePatientInfoResponse)(nil), // 5: database.SavePatientInfoResponse
	(*GetPatientRequest)(nil),       // 6: database.GetPatientRequest
	(*GetPatientResponse)(nil),      // 7: database.GetPatientResponse
	(*PatientInfo)(nil),             // 8: database.PatientInfo
}
var file_database_server_proto_depIdxs = []int32{
	8, // 0: database.SavePatientInfoRequest.patient_info:type_name -> database.PatientInfo
	8, // 1: database.GetPatientResponse.patient_info:type_name -> database.PatientInfo
	0, // 2: database.DatabaseService.Login:input_type -> database.LoginRequest
	2, // 3: database.DatabaseService.Register:input_type -> database.RegisterRequest
	4, // 4: database.DatabaseService.SavePatientInfo:input_type -> database.SavePatientInfoRequest
	6, // 5: database.DatabaseService.GetPatient:input_type -> database.GetPatientRequest
	1, // 6: database.DatabaseService.Login:output_type -> database.LoginResponse
	3, // 7: database.DatabaseService.Register:output_type -> database.RegisterResponse
	5, // 8: database.DatabaseService.SavePatientInfo:output_type -> database.SavePatientInfoResponse
	7, // 9: database.DatabaseService.GetPatient:output_type -> database.GetPatientResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_database_server_proto_init() }
func file_database_server_proto_init() {
	if File_database_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_server_proto_rawDesc), len(file_database_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_server_proto_goTypes,
		DependencyIndexes: file_database_server_proto_depIdxs,
		MessageInfos:      file_database_server_proto_msgTypes,
	}.Build()
	File_database_server_proto = out.File
	file_database_server_proto_goTypes = nil
	file_database_server_proto_depIdxs = nil
}
